"""Licensed real-Hex-Rays lifecycle smoke for viy's optional bridge.

The shell harness runs this script in headless IDAT with the bridge and the
IDA-native provider enabled.  The fixture's ``native_opposite_branches``
function yields an exact static fact, so rendering a ``[viy]`` header warning
proves that the bridge installed its C++ callback, published an immutable
snapshot, and participated in real decompilation.

If the selected processor has no licensed compatible decompiler, this test is
an explicit successful skip.  Every other missing callback/rendering outcome
is a failure.  A rendered cfunc is deliberately kept alive through qexit to
exercise bridge teardown order.
"""

import os
import time
import traceback

import ida_auto
import ida_hexrays
import ida_idaapi
import ida_kernwin
import ida_lines
import ida_loader
import ida_name
import ida_pro
import idautils


_HELD_HEXRAYS_OBJECTS = []
_STARTED = time.monotonic()
_ATTEMPTS = 0
_LAST_TEXT = ""
_TARGET_EA = None
_DEADLINE = _STARTED + max(
    2.0, int(os.environ.get("VIY_HEXRAYS_SMOKE_WAIT_MS", "10000"), 0) / 1000.0)


def _exit(code):
    ida_pro.qexit(code)
    return -1


def _function_named(fragment):
    for exact in (fragment, "_" + fragment):
        ea = ida_name.get_name_ea(ida_idaapi.BADADDR, exact)
        if ea != ida_idaapi.BADADDR:
            return ea
    for ea in idautils.Functions():
        if fragment in ida_name.get_name(ea):
            return ea
    return None


def _pseudocode_text(cfunc):
    lines = []
    for line in cfunc.get_pseudocode():
        rendered = getattr(line, "line", str(line))
        lines.append(ida_lines.tag_remove(rendered))
    return "\n".join(lines)


def _finish_with_live_objects(cfunc, text):
    global _HELD_HEXRAYS_OBJECTS
    view_state = "recent-cfunc"
    # Opening a UI pseudocode widget from text-mode IDAT is not a supported
    # lifecycle surface and can crash inside the decompiler independently of
    # viy's callback.  Keep the already-rendered reference-counted cfunc alive;
    # qexit must still remove viy's callback while that real cfunc is recent.
    _HELD_HEXRAYS_OBJECTS = [cfunc]

    annotation = next(line for line in text.splitlines() if "[viy]" in line)
    print("VIY_HEXRAYS_SMOKE annotation={} lifecycle={} attempts={}".format(
        annotation.strip(), view_state, _ATTEMPTS))

    # Yield once with the objects rooted globally.  qexit then destroys the
    # viy plugmod while the cfunc is still alive and recently rendered.
    if ida_kernwin.register_timer(100, lambda: _exit(0)) is None:
        return _exit(0)
    return -1


def _probe():
    global _ATTEMPTS, _LAST_TEXT
    _ATTEMPTS += 1
    try:
        # Bypass Hex-Rays' cfunc cache on every poll.  viy publishes at the end
        # of its timer-driven sweep, and hxe_collect_warnings runs when ctext is
        # generated by get_pseudocode().
        cfunc = ida_hexrays.decompile(
            _TARGET_EA, flags=ida_hexrays.DECOMP_NO_WAIT | ida_hexrays.DECOMP_NO_CACHE)
        if cfunc is not None:
            _LAST_TEXT = _pseudocode_text(cfunc)
            if "[viy]" in _LAST_TEXT:
                return _finish_with_live_objects(cfunc, _LAST_TEXT)
    except Exception:
        if time.monotonic() >= _DEADLINE:
            traceback.print_exc()

    if time.monotonic() < _DEADLINE:
        return 200

    print("VIY_HEXRAYS_SMOKE failure: no viy warning rendered for 0x{:x} after {} attempt(s)".format(
        _TARGET_EA, _ATTEMPTS))
    if _LAST_TEXT:
        print("VIY_HEXRAYS_SMOKE last_pseudocode_begin")
        print(_LAST_TEXT)
        print("VIY_HEXRAYS_SMOKE last_pseudocode_end")
    return _exit(1)


def _start():
    global _TARGET_EA
    ida_auto.auto_wait()

    # Kick PLUGIN_MULTI explicitly in case this freshly-created IDB was
    # already auto-analyzed before viy's listener observed auto_empty_finally.
    if not ida_loader.load_and_run_plugin("viy", 0):
        raise AssertionError("could not load/run the staged viy plugin")
    ida_auto.auto_wait()

    if not ida_hexrays.init_hexrays_plugin(0):
        print("VIY_HEXRAYS_SMOKE skipped: compatible licensed decompiler unavailable")
        _exit(0)
        return

    print("VIY_HEXRAYS_SMOKE api={} events=collect:{} hint:{}".format(
        ida_hexrays.get_hexrays_version(),
        ida_hexrays.hxe_collect_warnings, ida_hexrays.hxe_create_hint))

    _TARGET_EA = _function_named("native_opposite_branches")
    if _TARGET_EA is None:
        raise AssertionError("fixture function native_opposite_branches was not found")

    if ida_kernwin.register_timer(100, _probe) is None:
        # A no-timer IDAT causes viy itself to complete inline, so probe now.
        while time.monotonic() < _DEADLINE:
            if _probe() == -1:
                return
        raise AssertionError("inline Hex-Rays probe exhausted its deadline")


try:
    _start()
except Exception:
    traceback.print_exc()
    ida_pro.qexit(1)
